# Generated by Django 3.2.6 on 2021-12-17 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(default=uuid.uuid4, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Category name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, upload_to='images/category/icns/%Y/%m/%d')),
                ('image', models.ImageField(blank=True, upload_to='images/category/img/%Y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
