# Generated by Django 3.2.6 on 2021-12-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/category/icns/%Y/%m/%d'),
        ),
    ]
