# Generated by Django 3.2.6 on 2021-12-17 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('author', models.CharField(default='admin', max_length=50, verbose_name='Author')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(default='images/products/imgs/default_product_image.png', upload_to='images/products/imgs/%Y/%m/%d')),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField()),
                ('in_stock', models.BooleanField(default=True, verbose_name='In Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='categories.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ('-created',),
                'managed': True,
            },
        ),
    ]
